### ISSUE TITLE
.broker/clientAccess

### ISSUE THREAD

**Issue by fvacek** [silicon-heaven/shv-doc#10]
we have `.broker/clients/nn` already, please keep `clients` instead of `clientAccess`

**Comment by Cynerd** [comment]
That was something we decided that we can change, or not? You told me that this can be modified because it is not used anywhere. Or did you discover that it is used somewhere? The primary reason for the change is that `.broker/clients/nn/app` requires description of `.broker/clients` that would either be defined as just empty nodes. I think that here it is worth changing it if it is used only for maintenance purposes. Of course if you have some software that already uses it (shvbroker does not count in this sense) then I can see a reason.

**Comment by fvacek** [comment]
I just suggest to use `.broker/clients/123` instead of longer `.broker/clientAccess/123`.

**Comment by Cynerd** [comment]
I see. I do not have a huge issue with that. It makes sense. I only thought that you wouldn't give up the current clients representation.
